name = "rinha_ada"
version = "0.1.0"
description = "Ada backend and load balancer for Rinha 2025"
authors = ["cleisson abrbosa"]
maintainers = ["cleisson abrbosa <example@example.com>"]
maintainers-logins = ["cleissonbarbosa"]
licenses = "MIT"
website = ""
tags = []
executables = ["main_backend", "main_lb"]

[[depends-on]]
aws = "^24.0"