services:
  nginx:
    image: nginx:alpine
    container_name: rinha-nginx
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
    networks:
      - rinha-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

  backend1:
    image: rinha-ada-backend:latest
    container_name: rinha-backend1
    environment:
      - SERVER_PORT=8080
      - PAYMENT_PROCESSOR_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK=http://payment-processor-fallback:8080
      - REPLICA_PEERS=http://backend2:8080
    networks:
      - rinha-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "150MB"

  backend2:
    image: rinha-ada-backend:latest
    container_name: rinha-backend2
    environment:
      - SERVER_PORT=8080
      - PAYMENT_PROCESSOR_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK=http://payment-processor-fallback:8080
      - REPLICA_PEERS=http://backend1:8080
    networks:
      - rinha-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "150MB"

networks:
  rinha-network:
    driver: bridge
  payment-processor:
    external: true
