version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: rinha-nginx
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
    networks:
    - rinha-network
    - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "40MB"

  backend1:
    image: rinha-ada-backend:latest
    container_name: rinha-backend1
    environment:
      - SERVER_PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=rinha
      - DB_USER=rinha
      - DB_PASSWORD=rinha123
      - PAYMENT_PROCESSOR_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK=http://payment-processor-fallback:8080
    depends_on:
      - postgres
    networks:
    - rinha-network
    - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "100MB"

  backend2:
    image: rinha-ada-backend:latest
    container_name: rinha-backend2
    environment:
      - SERVER_PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=rinha
      - DB_USER=rinha
      - DB_PASSWORD=rinha123
      - PAYMENT_PROCESSOR_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK=http://payment-processor-fallback:8080
    depends_on:
      - postgres
    networks:
    - rinha-network
    - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "100MB"

  postgres:
    image: postgres:15-alpine
    container_name: rinha-postgres
    environment:
      - POSTGRES_DB=rinha
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=rinha123
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "90MB"

networks:
  rinha-network:
    driver: bridge
  payment-processor:
    external: true
